ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.erc20whaletrap]
path = "out/ERC20WhaleTrap.sol/ERC20WhaleTrap.json"
response_contract = "0xYourResponseContractAddress" # TODO: Replace with your deployed ERC20WhaleResponse contract address
response_function = "respondWithERC20Context(address,uint256,uint256,int256,int256)"
cooldown_period_blocks = 10
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 2
private_trap = true
whitelist = []